SELECT CAR_TYPE, COUNT(*) AS CARS
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS LIKE '%가죽시트%'  -- where 절에서는 = 연사자 사용 불가능
   OR OPTIONS LIKE '%열선시트%'
   OR OPTIONS LIKE '%통풍시트%'
GROUP BY CAR_TYPE  -- 차 종류별로 묶기
ORDER BY CAR_TYPE;