-- FISH_INFO와 FISH_NAME_INFO 테이블을 JOIN하여
-- 각 물고기 이름(FISH_NAME)과 그에 해당하는 ID, LENGTH 가져오기
SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH
FROM FISH_INFO FI
-- FISH_TYPE을 기준으로 FISH_INFO와 FISH_NAME_INFO를 조인
JOIN FISH_NAME_INFO FNI 
  ON FNI.FISH_TYPE = FI.FISH_TYPE

-- 서브쿼리: 각 FISH_TYPE에 대해 최대 LENGTH 값 찾기
JOIN (
    SELECT FNI.FISH_NAME, MAX(FI.LENGTH) AS MAX_LENGTH
    FROM FISH_INFO FI
    JOIN FISH_NAME_INFO FNI ON FNI.FISH_TYPE = FI.FISH_TYPE
    GROUP BY FNI.FISH_NAME  -- FISH_NAME별로 그룹화하여 각 물고기 이름에 대한 최대 LENGTH 찾기
) AS MaxLength
  ON FNI.FISH_NAME = MaxLength.FISH_NAME  -- FISH_NAME이 동일한 값을 가진 행 조인
  AND FI.LENGTH = MaxLength.MAX_LENGTH;  -- 해당 물고기 이름에 대해 최대 LENGTH를 가진 물고기만 선택
