SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH
FROM FISH_INFO FI
JOIN FISH_NAME_INFO FNI ON FNI.FISH_TYPE = FI.FISH_TYPE
JOIN (
    SELECT FNI.FISH_NAME, MAX(FI.LENGTH) AS MAX_LENGTH
    FROM FISH_INFO FI
    JOIN FISH_NAME_INFO FNI ON FNI.FISH_TYPE = FI.FISH_TYPE
    GROUP BY FNI.FISH_NAME
) AS MaxLength
ON FNI.FISH_NAME = MaxLength.FISH_NAME AND FI.LENGTH = MaxLength.MAX_LENGTH;