SELECT
    A.FOOD_TYPE,
    A.REST_ID,
    A.REST_NAME,
    A.FAVORITES
FROM REST_INFO A
WHERE FAVORITES = (
    SELECT MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO B
    WHERE A.FOOD_TYPE = B.FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC;

-- group by
SELECT
    A.FOOD_TYPE,
    A.REST_ID,
    A.REST_NAME,
    A.FAVORITES
FROM REST_INFO A
JOIN (
    SELECT
        FOOD_TYPE,
        MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) B ON B.FOOD_TYPE = A.FOOD_TYPE AND 
        B.FAVORITES = A.FAVORITES
ORDER BY FOOD_TYPE DESC;

-- 윈도우 함수
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (
    SELECT
        REST_ID,
        REST_NAME,
        FOOD_TYPE,
        FAVORITES,
        MAX(FAVORITES) OVER (PARTITION BY FOOD_TYPE) AS MAX_FAV
    FROM REST_INFO
) T
WHERE FAVORITES = MAX_FAV
ORDER BY FOOD_TYPE DESC;