SELECT
    CONCAT('/home/grep/src/', BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT)
    AS FILE_PATH
FROM (
    SELECT
        B.BOARD_ID,
        B.VIEWS,
        F.FILE_ID,
        F.FILE_NAME,
        F.FILE_EXT
    FROM USED_GOODS_BOARD B
    JOIN USED_GOODS_FILE F ON F.BOARD_ID = B.BOARD_ID
) T
WHERE T.VIEWS = (
    SELECT MAX(VIEWS)
    FROM USED_GOODS_BOARD
)
ORDER BY FILE_ID DESC;