-- COALESCE(A, B) : A의 NULL 값을 B로 대체하는 함수

SELECT
    COUNT(*) AS FISH_COUNT,
    MAX(LENGTH) AS MAX_LENGTH,
    FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(COALESCE(LENGTH, 10)) >= 33
ORDER BY FISH_TYPE


-- 윈도우 함수
SELECT
    FISH_COUNT,
    MAX_LENGTH,
    FISH_TYPE
FROM (
    SELECT
        ID,
        FISH_TYPE,
        LENGTH,
        TIME,
        COUNT(*) OVER (PARTITION BY FISH_TYPE) AS FISH_COUNT,
        MAX(IFNULL(LENGTH, 10)) OVER (PARTITION BY FISH_TYPE) AS MAX_LENGTH,
        AVG(IFNULL(LENGTH, 10)) OVER (PARTITION BY FISH_TYPE) AS AVG_LENGTH
    FROM FISH_INFO
) T
WHERE AVG_LENGTH >= 33
GROUP BY FISH_TYPE
ORDER BY FISH_TYPE;