SELECT
    MONTH,
    CAR_ID,
    MONTHLY_CNT AS RECORDS
FROM (
    SELECT
        CAR_ID,
        MONTH(START_DATE) AS MONTH,
        COUNT(*) OVER (PARTITION BY CAR_ID) AS TOTAL_CNT,
        COUNT(*) OVER (PARTITION BY CAR_ID, MONTH(START_DATE)) AS MONTHLY_CNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) >= 8 AND MONTH(START_DATE) <= 10
) T
WHERE TOTAL_CNT >= 5
GROUP BY CAR_ID, MONTH
ORDER BY MONTH, CAR_ID DESC