SELECT
    A.FOOD_TYPE,
    A.REST_ID,
    A.REST_NAME,
    A.FAVORITES
FROM REST_INFO A
WHERE FAVORITES = (
    SELECT MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO B
    WHERE A.FOOD_TYPE = B.FOOD_TYPE
    GROUP BY FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC;