SELECT
    ID,
    FISH_NAME,
    LENGTH
FROM (
    SELECT
        I.ID,
        I.FISH_TYPE,
        I.LENGTH,
        I.TIME,
        NI.FISH_NAME,
        MAX(I.LENGTH) OVER (PARTITION BY FISH_TYPE) AS MAX_LENGTH
    FROM FISH_INFO I
    JOIN FISH_NAME_INFO NI ON NI.FISH_TYPE = I.FISH_TYPE
) T
WHERE MAX_LENGTH = LENGTH
ORDER BY ID;