SELECT
    FH.FLAVOR
FROM FIRST_HALF FH
JOIN (
    SELECT
        J.FLAVOR,
        SUM(TOTAL_ORDER) AS FLAVOR_ORDER_SUM
    FROM JULY J
    GROUP BY FLAVOR
) S ON S.FLAVOR = FH.FLAVOR
ORDER BY S.FLAVOR_ORDER_SUM + FH.TOTAL_ORDER DESC
LIMIT 3;