SELECT
    CATEGORY,
    MAX_PRICE,
    PRODUCT_NAME
FROM (
    SELECT
        PRODUCT_NAME,
        CATEGORY,
        PRICE,
        MAX(PRICE) OVER (PARTITION BY CATEGORY) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
) T
WHERE PRICE = MAX_PRICE
ORDER BY MAX_PRICE DESC;